"""baseline_current_schema

Revision ID: 0001_baseline_current_schema
Revises:
Create Date: 2026-08-23

OBJ-006 (database-architect). Captures the CURRENT schema of all 4 tables
(users, verifications, rate_limit_hits, refresh_sessions) exactly as
produced by `Base.metadata.create_all` as of the end of OBJ-003 -- i.e.
every table/column/index/FK that exists in app/models/*.py the moment this
migration was authored, verified column-for-column against those model
files (not autogenerated against a live DB, since none of this project's
throwaway test databases should be treated as more authoritative than the
model source). No schema change is introduced by this migration -- it
exists purely to give Alembic a starting point that matches every
dev/test database already created via `create_all` up to this point.
See docs/database/obj-006-migration-plan.md section 1 for the ER diagram
this was derived from.

CUTOVER -- READ BEFORE RUNNING
===============================
Two distinct paths depending on whether the target database already has
these tables:

1. Fresh database (nothing created yet)::

       alembic upgrade head

   runs this migration's real ``CREATE TABLE`` statements, then 0002
   onward normally.

2. Existing dev/test database that already has these 4 tables via
   ``Base.metadata.create_all`` (every environment from OBJ-000 through
   OBJ-005 today)::

       alembic stamp 0001_baseline_current_schema
       alembic upgrade head

   ``stamp`` records this revision as applied in the ``alembic_version``
   table WITHOUT executing its DDL -- the tables already exist and are
   column-for-column identical to what this migration would create.
   ``upgrade head`` then applies 0002 onward normally. Running
   ``alembic upgrade head`` directly against such a database (skipping
   the stamp step) WILL fail with "relation ... already exists".

See tests/README.md for copy-pasteable commands covering the test suite
specifically (running it against a migrated schema vs. against
``create_all``).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline_current_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        # OBJ-002 (audit finding #3): bumped on /auth/reset-password to
        # invalidate every access/refresh token issued before the bump.
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "verifications",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        # HMAC-SHA256 hex digest (OBJ-003 finding #7), 64 chars, stored in an
        # unbounded String column -- matches app/models/verification.py.
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        # OBJ-001 (audit finding #2): shared failed-attempt counter across
        # /verify-otp and /reset-password.
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_verifications_email", "verifications", ["email"], unique=False
    )

    op.create_table(
        "rate_limit_hits",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        # No server_default (python-side only, caller-supplied) -- matches
        # app/models/rate_limit.py's documented freezegun-consistency
        # rationale. Migration 0005 optionally converges this.
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_rate_limit_hits_scope_ip_email_created_at",
        "rate_limit_hits",
        ["scope", "ip", "email", "created_at"],
        unique=False,
    )

    op.create_table(
        "refresh_sessions",
        # == the `jti` claim of the refresh token this row represents.
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, nullable=False),
        # Constant across a rotation chain; == id of the row created at login.
        sa.Column("family_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        # NULL = active; set on rotation-supersession, logout, reuse-
        # triggered family revocation, or password-reset bulk revocation.
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        # Audit-trail pointer set at rotation time; not required for
        # correctness (family_id + revoked_at already suffice for the
        # reuse-detection state machine).
        sa.Column("replaced_by", pg.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="refresh_sessions_user_id_fkey",
            # NO ACTION today (SQLAlchemy/Postgres default when no ondelete
            # is specified) -- migration 0004 changes this to CASCADE.
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["refresh_sessions.id"],
            name="refresh_sessions_replaced_by_fkey",
            # NO ACTION today -- migration 0004 changes this to SET NULL.
        ),
    )
    op.create_index(
        "ix_refresh_sessions_family_id", "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index(
        "ix_refresh_sessions_user_id_revoked_at",
        "refresh_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )


def downgrade() -> None:
    # refresh_sessions first: it FKs to users and to itself.
    op.drop_table("refresh_sessions")
    op.drop_table("rate_limit_hits")
    op.drop_table("verifications")
    op.drop_table("users")
